spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:0.0.0.0}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:clothing_marketplace}
    username: ${POSGRESQL_USERNAME:gersi}
    password: ${POSGRESQL_PASSWORD:gersi}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true