version: '3.8'
name: clothing_marketplace_db

services:
  postgres:
    container_name: postgres_container_v2
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gersi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gersi}
      POSTGRES_DB: ${POSTGRES_DB:-clothing_marketplace}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-gersi}"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    container_name: pgadmin_container_v2
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-gersimuca@aol.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-gersimuca}
      PGADMIN_DEFAULT_ADDRESS: 6000
      PGADMIN_LISTEN_PORT: 6000
    expose:
      - "6000"
    ports:
      - "7000:6000"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgadmin_volume:
  postgres_volume:

